jobs:
  include:
    - stage: test
      services:
        - docker
      before_install:
        - docker network create gatehouse_default
        - docker-compose -f docker-compose-development.yaml pull
        - docker-compose -f docker-compose-development.yaml create
        - docker-compose -f docker-compose-development.yaml start
      language: elixir
      elixir:
        - 1.9
      otp_release:
        - 22.0
      env:
        - MIX_ENV=test
      script: mix test

    - stage: build
      services:
        - docker
      script:
        - ./build.sh
        - ./build-docker-release.sh
        - ./deploy-to-docker-repo.sh

stages:
  - test
  - name: build
    if: branch = master
