---
version: "2.1"

services:
  gatehouse-db:
    container_name: gatehouse-db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gatehouse
      MYSQL_DATABASE: gatehouse
      MYSQL_USER: gatehouse
      MYSQL_PASSWORD: gatehouse
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--password=gatehouse", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
  gatehouse-app:
    container_name: gatehouse-app
    image: thomasvolk-docker-public.bintray.io/gatehouse/gatehouse:latest
    ports:
      - "9998:9998"
    restart: always
    environment:
      REPLACE_OS_VARS: 'true'
      PORT: 9998
      GATEHOUSE_WEB_SECRET_KEY_BASE: Dn0MUHCWLaC1zC6JnAWqZrl5hs2M71f8F6PxXTPfJXAc8Lv82OYcV/uwuB42YA9K
      GATEHOUSE_DB_HOST: gatehouse-db
      GATEHOUSE_DB_NAME: gatehouse
      GATEHOUSE_DB_USER: gatehouse
      GATEHOUSE_DB_PASSWORD: gatehouse
      GATEHOUSE_DB_PORT: 3306
      GATEHOUSE_AUTH_SECRET_KEY: dev_A1yzSKfmfiQgwZ08vIeuXUQqkG8
      GATEHOUSE_AUTH_TOKEN_TTL: 3600
    depends_on:
      gatehouse-db:
        condition: service_healthy
