FROM ubuntu:18.04
COPY gatehouse.tar.gz /tmp/
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl \
    && rm -rf /var/lib/apt/lists/*
RUN cd /usr/local/lib/ \
       && mkdir gatehouse \
       && cd gatehouse \
       && tar xfz /tmp/gatehouse.tar.gz
CMD [ "sh", "-c", "/usr/local/lib/gatehouse/bin/gatehouse command Elixir.Gatehouse.Release.Tasks migrate \
                   && /usr/local/lib/gatehouse/bin/gatehouse foreground" ]
