FROM library/elixir:1.9
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs
COPY . .
RUN rm -Rf _build
RUN export MIX_ENV=prod && \
    mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix clean && \
    (cd assets && npm install && ./node_modules/brunch/bin/brunch build -p) && \
    mix release && \
    (cd _build/prod/rel/gatehouse/ && tar cfz ../../../../gatehouse.tar.gz .)