---
version: "2"

services:
  db:
    container_name: dev-gatehouse-db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gatehouse
      MYSQL_DATABASE: gatehouse
      MYSQL_USER: gatehouse
      MYSQL_PASSWORD: gatehouse
    ports:
      - "13306:3306"
  example-python-app:
    container_name: dev-example-python-app
    build: ./example/python/
    environment:
      GATEHOUSE_URL: http://localhost:4000
      PORT: 8001
    ports:
      - "8001:8001"